### ISSUE TITLE
Testimonials

### ISSUE THREAD

**Issue by phoebeW17** [phoebeW17/project-planning-demo#2]
### Testimonials

User story: As a community member, I want to read testimonials from previous attendees so that I can feel confident about attending events.

**Acceptance Criteria:**

- [ ] The testimonials page displays at least five client testimonials.

- [ ] Each testimonial includes the client's first name, year of event, with pictures and comments.

- [ ] The testimonials section is responsive and looks good on multiple device sizes.

**Tasks:**

- [ ] Create an HTML section for testimonials.

- [ ] Style the testimonials section using CSS and Bootstrap.

- [ ] Use Bootstrap's grid system to make sure the testimonials section is responsive.
